# -*- coding: utf-8 -*-
"""Dataset Training (FeasTapp).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-A80AguIsvpSqkbNRWs_NaDSaikBsKfs
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

!pip install tensorflow

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional
from keras.optimizers import SGD
import math
from sklearn.metrics import mean_squared_error

from ultralytics import YOLO

model = YOLO("yolov8m.pt")

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

model.train(data="/content/drive/MyDrive/THESIS/Thesis Writing 1/Dataset/Ingredients/YoloV8Train/data.yaml", epochs=30)

